"""
字段配置 — 多源 API 字段总表的代码化版本
从 field_list/多源API字段总表（去重合并）.md 生成

每个字段记录：
  - type: 数据库列类型（String/Integer/Boolean/Float/JSON）
  - priority: 多源冲突时优先使用哪个源的字段值
"""

# ── 字段配置 ────────────────────────────────────────────────────
# key = 数据库模型列名
# type = SQLAlchemy 列类型
# priority = "keepa" / "rainforest" / "canopy"（多源冲突时优先）
FIELD_CONFIG = {
    # ═══ 基础标识 ═══
    "asin": {"type": "String", "priority": "rainforest"},
    "parent_asin": {"type": "String", "priority": "rainforest"},
    "title": {"type": "String", "priority": "rainforest"},
    "brand": {"type": "String", "priority": "rainforest"},
    "link": {"type": "String", "priority": "rainforest"},
    "manufacturer": {"type": "String", "priority": "rainforest"},
    "model_number": {"type": "String", "priority": "rainforest"},
    "part_number": {"type": "String", "priority": "keepa"},
    "sub_title": {"type": "JSON", "priority": "rainforest"},
    "search_alias": {"type": "JSON", "priority": "rainforest"},
    "keywords": {"type": "String", "priority": "rainforest"},
    "keywords_list": {"type": "JSON", "priority": "rainforest"},
    "product_group": {"type": "String", "priority": "keepa"},
    "product_type": {"type": "String", "priority": "keepa"},
    "product_type_name": {"type": "String", "priority": "rainforest"},
    "type": {"type": "String", "priority": "keepa"},
    "binding": {"type": "String", "priority": "keepa"},
    "format": {"type": "String", "priority": "rainforest"},
    "edition": {"type": "String", "priority": "keepa"},
    "authors": {"type": "JSON", "priority": "rainforest"},
    "runtime": {"type": "String", "priority": "rainforest"},
    "is_bundle": {"type": "Boolean", "priority": "rainforest"},
    "is_collection": {"type": "Boolean", "priority": "rainforest"},
    "collection_size": {"type": "Float", "priority": "rainforest"},
    "collection_children": {"type": "JSON", "priority": "rainforest"},
    "first_available": {"type": "JSON", "priority": "rainforest"},
    "publication_date": {"type": "String", "priority": "rainforest"},
    "publisher": {"type": "String", "priority": "rainforest"},
    "isbn_10": {"type": "String", "priority": "rainforest"},
    "isbn_13": {"type": "String", "priority": "rainforest"},
    "language": {"type": "String", "priority": "rainforest"},
    "reading_age": {"type": "String", "priority": "rainforest"},
    "series": {"type": "JSON", "priority": "rainforest"},
    "kindle_unlimited": {"type": "Boolean", "priority": "rainforest"},
    "audible_sample": {"type": "String", "priority": "rainforest"},
    "read_sample": {"type": "JSON", "priority": "rainforest"},
    "book_description": {"type": "String", "priority": "rainforest"},
    "marketplace_id": {"type": "String", "priority": "rainforest"},
    "title_excluding_variant_name": {"type": "String", "priority": "rainforest"},
    "parent_title": {"type": "String", "priority": "keepa"},
    "website_display_group": {"type": "String", "priority": "keepa"},
    "website_display_group_name": {"type": "String", "priority": "keepa"},
    "domain_id": {"type": "Integer", "priority": "keepa"},
    "g": {"type": "Integer", "priority": "keepa"},

    # ═══ 商品属性 ═══
    "color": {"type": "String", "priority": "rainforest"},
    "size": {"type": "String", "priority": "keepa"},
    "style": {"type": "String", "priority": "rainforest"},
    "material": {"type": "String", "priority": "rainforest"},
    "materials": {"type": "JSON", "priority": "keepa"},
    "weight": {"type": "String", "priority": "rainforest"},
    "dimensions": {"type": "String", "priority": "rainforest"},
    "shipping_weight": {"type": "String", "priority": "rainforest"},
    "item_weight_g": {"type": "Integer", "priority": "keepa"},
    "item_height_mm": {"type": "Integer", "priority": "keepa"},
    "item_length_mm": {"type": "Integer", "priority": "keepa"},
    "item_width_mm": {"type": "Integer", "priority": "keepa"},
    "package_weight_g": {"type": "Integer", "priority": "keepa"},
    "package_height_mm": {"type": "Integer", "priority": "keepa"},
    "package_length_mm": {"type": "Integer", "priority": "keepa"},
    "package_width_mm": {"type": "Integer", "priority": "keepa"},
    "package_quantity": {"type": "Integer", "priority": "keepa"},
    "number_of_items": {"type": "Integer", "priority": "keepa"},
    "unit_count": {"type": "JSON", "priority": "keepa"},
    "item_type_keyword": {"type": "String", "priority": "keepa"},
    "batteries_included": {"type": "Boolean", "priority": "keepa"},
    "batteries_required": {"type": "Boolean", "priority": "keepa"},
    "has_size_guide": {"type": "Boolean", "priority": "rainforest"},
    "size_guide_html": {"type": "String", "priority": "rainforest"},
    "energy_efficiency": {"type": "JSON", "priority": "rainforest"},
    "ingredients": {"type": "JSON", "priority": "rainforest"},
    "diet_type": {"type": "JSON", "priority": "rainforest"},
    "attributes": {"type": "JSON", "priority": "rainforest"},
    "specific_uses_for_product": {"type": "JSON", "priority": "keepa"},
    "recommended_uses_for_product": {"type": "String", "priority": "keepa"},
    "special_features": {"type": "JSON", "priority": "keepa"},
    "hazardous_materials": {"type": "JSON", "priority": "keepa"},
    "languages": {"type": "JSON", "priority": "keepa"},
    "proposition_65_warning": {"type": "Boolean", "priority": "rainforest"},
    "add_on_item": {"type": "JSON", "priority": "rainforest"},
    "sell_on_amazon": {"type": "Boolean", "priority": "rainforest"},
    "has_360_view": {"type": "Boolean", "priority": "rainforest"},

    # ═══ Listing ═══
    "feature_bullets": {"type": "JSON", "priority": "rainforest"},
    "feature_bullets_count": {"type": "Integer", "priority": "rainforest"},
    "feature_bullets_flat": {"type": "String", "priority": "rainforest"},
    "description": {"type": "String", "priority": "rainforest"},
    "rich_product_description": {"type": "JSON", "priority": "rainforest"},
    "whats_in_the_box": {"type": "JSON", "priority": "rainforest"},
    "specifications": {"type": "JSON", "priority": "rainforest"},
    "specifications_flat": {"type": "String", "priority": "rainforest"},
    "url_slug": {"type": "String", "priority": "keepa"},
    "information": {"type": "String", "priority": "rainforest"},
    "services": {"type": "JSON", "priority": "rainforest"},
    "documents": {"type": "JSON", "priority": "rainforest"},
    "editorial_reviews": {"type": "JSON", "priority": "rainforest"},
    "important_information": {"type": "JSON", "priority": "rainforest"},
    "additional_details": {"type": "JSON", "priority": "rainforest"},
    "gift_guide_badge": {"type": "JSON", "priority": "rainforest"},
    "amazons_choice": {"type": "JSON", "priority": "rainforest"},
    "bestseller_badge": {"type": "JSON", "priority": "rainforest"},
    "deal_badge": {"type": "String", "priority": "rainforest"},
    "product_deal": {"type": "JSON", "priority": "rainforest"},
    "promotions_feature": {"type": "String", "priority": "rainforest"},

    # ═══ 图片视频 ═══
    "main_image": {"type": "JSON", "priority": "rainforest"},
    "images": {"type": "JSON", "priority": "rainforest"},
    "images_count": {"type": "Integer", "priority": "rainforest"},
    "images_flat": {"type": "String", "priority": "rainforest"},
    "image_overlay_badge": {"type": "JSON", "priority": "rainforest"},
    "videos": {"type": "JSON", "priority": "rainforest"},
    "videos_count": {"type": "Integer", "priority": "rainforest"},
    "videos_flat": {"type": "String", "priority": "rainforest"},
    "videos_additional": {"type": "JSON", "priority": "rainforest"},

    # ═══ 品牌 ═══
    "brand_store": {"type": "JSON", "priority": "rainforest"},
    "brand_store_name": {"type": "String", "priority": "keepa"},
    "brand_store_url": {"type": "String", "priority": "keepa"},
    "brand_store_url_name": {"type": "String", "priority": "keepa"},
    "store_name": {"type": "String", "priority": "rainforest"},
    "store_id": {"type": "String", "priority": "rainforest"},

    # ═══ 类目 ═══
    "categories": {"type": "JSON", "priority": "rainforest"},
    "categories_flat": {"type": "String", "priority": "rainforest"},
    "category_tree": {"type": "JSON", "priority": "rainforest"},
    "category_name": {"type": "String", "priority": "rainforest"},
    "bsr_category": {"type": "String", "priority": "rainforest"},
    "bsr_category_id": {"type": "String", "priority": "keepa"},
    "root_category": {"type": "String", "priority": "keepa"},
    "root_category_id": {"type": "String", "priority": "keepa"},
    "sales_rank_reference_id": {"type": "String", "priority": "keepa"},
    "sales_rank_reference_history": {"type": "JSON", "priority": "keepa"},
    "sales_rank_display_group": {"type": "String", "priority": "keepa"},
    "category_information": {"type": "JSON", "priority": "rainforest"},

    # ═══ 价格 ═══
    "current_price": {"type": "Float", "priority": "keepa"},
    "currency": {"type": "String", "priority": "keepa"},
    "list_price": {"type": "Float", "priority": "rainforest"},
    "buybox_price": {"type": "Float", "priority": "keepa"},
    "avg_price_30d": {"type": "Float", "priority": "keepa"},
    "avg_price_90d": {"type": "Float", "priority": "keepa"},
    "avg_price_180d": {"type": "Float", "priority": "keepa"},
    "avg_price_365d": {"type": "Float", "priority": "keepa"},
    "min_price_30d": {"type": "Float", "priority": "keepa"},
    "min_price_90d": {"type": "Float", "priority": "keepa"},
    "min_price_180d": {"type": "Float", "priority": "keepa"},
    "max_price_90d": {"type": "Float", "priority": "keepa"},
    "max_price_180d": {"type": "Float", "priority": "keepa"},
    "is_lowest_price": {"type": "Boolean", "priority": "keepa"},
    "buybox_is_amazon": {"type": "Boolean", "priority": "keepa"},
    "buybox_is_prime_eligible": {"type": "Boolean", "priority": "keepa"},
    "buybox_shipping": {"type": "Float", "priority": "keepa"},
    "has_coupon": {"type": "Boolean", "priority": "rainforest"},
    "unit_price": {"type": "String", "priority": "rainforest"},
    "buybox_winner": {"type": "JSON", "priority": "rainforest"},
    "price": {"type": "JSON", "priority": "rainforest"},
    "prices": {"type": "JSON", "priority": "rainforest"},
    "rrp": {"type": "JSON", "priority": "rainforest"},
    "shipping": {"type": "JSON", "priority": "rainforest"},
    "condition": {"type": "JSON", "priority": "rainforest"},
    "save": {"type": "JSON", "priority": "rainforest"},
    "one_time_price": {"type": "JSON", "priority": "rainforest"},
    "mixed_offers_count": {"type": "Integer", "priority": "rainforest"},
    "mixed_offers_from": {"type": "JSON", "priority": "rainforest"},
    "is_big_spring_deal": {"type": "Boolean", "priority": "rainforest"},
    "big_spring_deal_percentage": {"type": "Float", "priority": "rainforest"},
    "amazon_discount": {"type": "JSON", "priority": "rainforest"},
    "unqualified_buy_box": {"type": "Boolean", "priority": "rainforest"},
    "deal": {"type": "JSON", "priority": "rainforest"},
    "vat": {"type": "JSON", "priority": "rainforest"},
    "eligible_free_international_delivery": {"type": "Boolean", "priority": "rainforest"},
    "free_shipping_minimum_spend": {"type": "String", "priority": "rainforest"},

    # ═══ 评论评分 ═══
    "rating": {"type": "Float", "priority": "rainforest"},
    "ratings_total": {"type": "Integer", "priority": "rainforest"},
    "review_count": {"type": "Integer", "priority": "keepa"},
    "rating_history": {"type": "JSON", "priority": "keepa"},
    "review_count_history": {"type": "JSON", "priority": "keepa"},
    "rating_breakdown": {"type": "JSON", "priority": "rainforest"},
    "top_reviews": {"type": "JSON", "priority": "rainforest"},
    "reviews": {"type": "JSON", "priority": "rainforest"},
    "review_velocity_30d": {"type": "Integer", "priority": "keepa"},
    "has_reviews": {"type": "Boolean", "priority": "keepa"},
    "summarization_attributes": {"type": "JSON", "priority": "rainforest"},
    "customers_say": {"type": "JSON", "priority": "rainforest"},
    "safety_product_resources": {"type": "JSON", "priority": "rainforest"},
    "ratings_total": {"type": "Integer", "priority": "rainforest"},

    # ═══ Offer/卖家 ═══
    "seller_count": {"type": "Integer", "priority": "keepa"},
    "offer_count": {"type": "Integer", "priority": "keepa"},
    "offer_count_fba": {"type": "Integer", "priority": "keepa"},
    "offer_count_fbm": {"type": "Integer", "priority": "keepa"},
    "buybox_seller_id": {"type": "String", "priority": "keepa"},
    "buybox_seller_name": {"type": "String", "priority": "keepa"},
    "buybox_availability": {"type": "String", "priority": "rainforest"},
    "buybox_condition": {"type": "String", "priority": "rainforest"},
    "seller_ids_lowest_fba": {"type": "JSON", "priority": "keepa"},
    "seller_ids_lowest_fbm": {"type": "JSON", "priority": "keepa"},
    "buybox_eligible_offer_counts": {"type": "JSON", "priority": "keepa"},
    "seller_profile": {"type": "String", "priority": "rainforest"},
    "top_seller_id": {"type": "String", "priority": "keepa"},
    "top_seller_name": {"type": "String", "priority": "keepa"},
    "has_amazon_selling": {"type": "Boolean", "priority": "keepa"},
    "has_china_sellers": {"type": "Boolean", "priority": "keepa"},
    "is_sold_by_amazon": {"type": "Boolean", "priority": "rainforest"},
    "is_prime_excl": {"type": "Boolean", "priority": "keepa"},
    "is_shippable": {"type": "Boolean", "priority": "keepa"},
    "is_map": {"type": "Boolean", "priority": "keepa"},
    "ships_from_china": {"type": "Boolean", "priority": "keepa"},
    "minimum_order_quantity": {"type": "JSON", "priority": "keepa"},
    "max_order_quantity": {"type": "JSON", "priority": "rainforest"},
    "last_seen": {"type": "Integer", "priority": "keepa"},
    "last_stock_update": {"type": "Integer", "priority": "keepa"},
    "offer_csv": {"type": "JSON", "priority": "keepa"},
    "prime_excl_csv": {"type": "JSON", "priority": "keepa"},
    "offers_successful": {"type": "Boolean", "priority": "keepa"},
    "buybox_is_fba": {"type": "Boolean", "priority": "keepa"},
    "buybox_shipping_country": {"type": "String", "priority": "keepa"},
    "offer_asin": {"type": "String", "priority": "rainforest"},
    "position": {"type": "Integer", "priority": "rainforest"},
    "promotion": {"type": "JSON", "priority": "rainforest"},
    "import_fee": {"type": "JSON", "priority": "rainforest"},
    "undeliverable": {"type": "Boolean", "priority": "rainforest"},
    "undeliverable_message": {"type": "String", "priority": "rainforest"},
    "product": {"type": "JSON", "priority": "rainforest"},
    "offers": {"type": "JSON", "priority": "rainforest"},
    "available_filters": {"type": "JSON", "priority": "rainforest"},
    "pagination": {"type": "JSON", "priority": "rainforest"},

    # ═══ BSR ═══
    "current_bsr": {"type": "Integer", "priority": "keepa"},
    "avg_bsr_30d": {"type": "Float", "priority": "keepa"},
    "avg_bsr_90d": {"type": "Float", "priority": "keepa"},
    "avg_bsr_180d": {"type": "Float", "priority": "keepa"},
    "avg_bsr_365d": {"type": "Float", "priority": "keepa"},
    "bsr_trend": {"type": "String", "priority": "keepa"},
    "sales_rank_drops_30d": {"type": "Integer", "priority": "keepa"},
    "sales_rank_drops_90d": {"type": "Integer", "priority": "keepa"},
    "sales_rank_drops_180d": {"type": "Integer", "priority": "keepa"},
    "sales_rank_drops_365d": {"type": "Integer", "priority": "keepa"},
    "monthly_sold": {"type": "Integer", "priority": "keepa"},
    "weekly_sold": {"type": "Integer", "priority": "keepa"},
    "annual_sold": {"type": "Integer", "priority": "keepa"},
    "sales_rank_history": {"type": "JSON", "priority": "keepa"},
    "bestsellers_rank": {"type": "JSON", "priority": "rainforest"},
    "bestsellers_rank_flat": {"type": "String", "priority": "rainforest"},
    "bestseller": {"type": "JSON", "priority": "rainforest"},
    "sales_ranks": {"type": "JSON", "priority": "keepa"},

    # ═══ 变体 ═══
    "child_asins": {"type": "JSON", "priority": "rainforest"},
    "variant_asins_flat": {"type": "String", "priority": "rainforest"},
    "variations": {"type": "JSON", "priority": "rainforest"},
    "variation_csv": {"type": "String", "priority": "keepa"},
    "parent_asin_history": {"type": "JSON", "priority": "keepa"},

    # ═══ A+ ═══
    "aplus_content": {"type": "JSON", "priority": "rainforest"},

    # ═══ 促销 ═══
    "coupon": {"type": "JSON", "priority": "rainforest"},
    "coupon_text": {"type": "String", "priority": "rainforest"},
    "promotions_json": {"type": "JSON", "priority": "rainforest"},
    "lightning_deal_info": {"type": "JSON", "priority": "keepa"},
    "coupon": {"type": "JSON", "priority": "rainforest"},
    "gift_guide": {"type": "JSON", "priority": "rainforest"},
    "deal": {"type": "JSON", "priority": "rainforest"},
    "subscribe_and_save": {"type": "JSON", "priority": "rainforest"},
    "climate_pledge_friendly": {"type": "Boolean", "priority": "rainforest"},
    "is_exclusive_to_amazon": {"type": "Boolean", "priority": "rainforest"},
    "is_small_business": {"type": "Boolean", "priority": "rainforest"},
    "is_amazon_brand": {"type": "Boolean", "priority": "rainforest"},
    "featured_from_our_brands": {"type": "Boolean", "priority": "rainforest"},
    "is_fulfilled_by_amazon_international": {"type": "Boolean", "priority": "rainforest"},
    "is_amazon_fresh": {"type": "Boolean", "priority": "rainforest"},
    "is_whole_foods_market": {"type": "Boolean", "priority": "rainforest"},
    "prime_video": {"type": "Boolean", "priority": "rainforest"},
    "deal_badge": {"type": "String", "priority": "rainforest"},
    "big_spring_deal_percentage": {"type": "Float", "priority": "rainforest"},

    # ═══ 配送物流 ═══
    "fulfillment": {"type": "JSON", "priority": "rainforest"},
    "availability": {"type": "JSON", "priority": "rainforest"},
    "availability_text": {"type": "String", "priority": "keepa"},
    "return_policy": {"type": "JSON", "priority": "rainforest"},
    "protection_plans": {"type": "JSON", "priority": "rainforest"},
    "shipping_origin": {"type": "String", "priority": "keepa"},
    "available_prime_exclusive": {"type": "String", "priority": "keepa"},
    "is_eligible_for_free_shipping": {"type": "Boolean", "priority": "keepa"},
    "is_heat_sensitive": {"type": "Boolean", "priority": "keepa"},
    "is_fulfilled_by_amazon_international": {"type": "Boolean", "priority": "rainforest"},
    "isEligibleForSuperSaverShipping": {"type": "Boolean", "priority": "keepa"},
    "delivery": {"type": "JSON", "priority": "rainforest"},

    # ═══ 时间戳 ═══
    "listed_since": {"type": "String", "priority": "keepa"},
    "tracking_since": {"type": "String", "priority": "keepa"},
    "last_update": {"type": "Integer", "priority": "keepa"},
    "last_price_change": {"type": "Integer", "priority": "keepa"},
    "last_rating_update": {"type": "Integer", "priority": "keepa"},
    "last_ebay_update": {"type": "Integer", "priority": "keepa"},
    "release_date": {"type": "Integer", "priority": "keepa"},

    # ═══ FBA 费用 ═══
    "fba_fee": {"type": "Float", "priority": "keepa"},
    "referral_fee_percent": {"type": "Integer", "priority": "keepa"},
    "referral_fee_percentage": {"type": "Float", "priority": "keepa"},

    # ═══ 库存 ═══
    "stock_level": {"type": "Integer", "priority": "rainforest"},
    "is_in_stock": {"type": "Boolean", "priority": "rainforest"},
    "out_of_stock_pct_30d": {"type": "Float", "priority": "keepa"},
    "out_of_stock_pct_90d": {"type": "Float", "priority": "keepa"},
    "out_of_stock_pct_180d": {"type": "Float", "priority": "keepa"},
    "out_of_stock_count_amazon": {"type": "Integer", "priority": "keepa"},

    # ═══ 搜索专用 ═══
    "search_results": {"type": "JSON", "priority": "rainforest"},
    "search_information": {"type": "JSON", "priority": "rainforest"},
    "ad_blocks": {"type": "JSON", "priority": "rainforest"},
    "video_blocks": {"type": "JSON", "priority": "rainforest"},
    "related_searches": {"type": "JSON", "priority": "rainforest"},
    "related_brands": {"type": "JSON", "priority": "rainforest"},
    "refinements": {"type": "JSON", "priority": "rainforest"},
    "shopping_advisors": {"type": "JSON", "priority": "rainforest"},
    "sponsored": {"type": "Boolean", "priority": "rainforest"},
    "is_carousel": {"type": "Boolean", "priority": "rainforest"},
    "carousel": {"type": "JSON", "priority": "rainforest"},
    "recent_sales": {"type": "String", "priority": "rainforest"},
    "recent_views": {"type": "String", "priority": "rainforest"},
    "other_formats": {"type": "JSON", "priority": "rainforest"},
    "narrated_by": {"type": "JSON", "priority": "rainforest"},
    "image": {"type": "String", "priority": "rainforest"},

    # ═══ 请求元数据 ═══
    "request_info": {"type": "JSON", "priority": "rainforest"},
    "request_parameters": {"type": "JSON", "priority": "rainforest"},
    "request_metadata": {"type": "JSON", "priority": "rainforest"},

    # ═══ 其他配置字段 ═══
    "also_bought": {"type": "JSON", "priority": "rainforest"},
    "also_viewed": {"type": "JSON", "priority": "rainforest"},
    "frequently_bought_together": {"type": "JSON", "priority": "rainforest"},
    "sponsored_products": {"type": "JSON", "priority": "rainforest"},
    "new_offers_from": {"type": "String", "priority": "rainforest"},
    "used_offers_count": {"type": "Integer", "priority": "rainforest"},
    "used_offers_from": {"type": "String", "priority": "rainforest"},
    "trade_in_and_save": {"type": "Boolean", "priority": "rainforest"},
    "country_of_origin": {"type": "String", "priority": "rainforest"},
    "recent_sales": {"type": "String", "priority": "rainforest"},

    # ETL 内部字段
    "domain": {"type": "String", "priority": "keepa"},
    "data_source": {"type": "JSON", "priority": "keepa"},
}


# ── 从 FIELD_CONFIG 生成 _SOURCE_PRIORITY ──
_SOURCE_PRIORITY = {
    name: cfg["priority"]
    for name, cfg in FIELD_CONFIG.items()
}